# Generated by Django 6.0.6 on 2026-07-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Uskuna kategoriyasi',
                'verbose_name_plural': 'Uskuna kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsifi', models.TextField(blank=True)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('narxi_diapazoni', models.CharField(blank=True, max_length=100)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uskunalar', to='equipment.equipmentcategory')),
            ],
        ),
    ]
