# Generated by Django 6.0.6 on 2026-07-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('til', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Ruscha')], max_length=2)),
                ('turi', models.CharField(choices=[('kitob', 'Kitob/Darslik'), ('shablon', 'Hujjat namunasi')], max_length=10)),
                ('tavsifi', models.TextField(blank=True)),
                ('fayl', models.FileField(upload_to='materials/')),
                ('muqova_rasm', models.ImageField(blank=True, null=True, upload_to='material_covers/')),
                ('yuklangan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'ordering': ['-yuklangan_sana'],
            },
        ),
    ]
