# Generated by Django 6.0.6 on 2026-07-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Kurs kategoriyasi',
                'verbose_name_plural': 'Kurs kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('tavsifi', models.TextField()),
                ('muqova_rasm', models.ImageField(blank=True, null=True, upload_to='course_covers/')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to='courses.coursecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('matn', models.TextField(blank=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('tartib_raqami', models.PositiveIntegerField(default=0)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darslar', to='courses.course')),
            ],
            options={
                'ordering': ['tartib_raqami'],
            },
        ),
    ]
